### PR TITLE
Bug fixing minors

### LINKED ISSUE #79: Long names in address book cause problems with scaling
**Steps to reproduce**
Make a long name in the address book

**Current behavior**
When displaying the name the app appears wonky. 
 
**Affected Version**
Android and iOS

**Screenshots**
image

image

I have a screenshot for iOS at https://github.com/nemgrouplimited/symbol-mobile-wallet/issues/71#issuecomment-745609456

### PR DESCRIPTION
**Pull request by Peersyst**
Resolved: #94 
Resolved: #96 
Resolved: #97 
Resolved: #98 
Resolved: #79
Resolved: #74
Resolved: #89
Resolved: #4
Resolved: #57
Resolved: #87
Resolved: #43
Resolved: #69
Resolved: #97
Resolved: #75
Resolved: #36

### CODE REVIEW

File: src/store/transfer.js [hunk 1]
```diff
@@ -72,6 +72,7 @@ export default {
                 type: 'transfer/setTransaction',
                 payload: {
                     ...transactionModel,
+                    displayFee: ttxWithFee.maxFee.compact() / Math.pow(10, 6),
```
Comment (OlegMakarenko) [inline src/store/transfer.js:75]: I think it is better to move the `fee` formatter to services or utils

**Review by OlegMakarenko — APPROVED** [review]
