### PR TITLE
Harvesting refactored

### LINKED ISSUE #29: [iOS/Android][Harvesting] Selected node is not visible
WTR:
1. Go to Harvesting page
2. Choose any node and start harvesting 
3. Close the app and open it again

Result: Selected node is not visible 

image
image

### LINKED ISSUE #77: App always says "Activation in progress" in the harvesting section.
I guess it goes without saying and it is being looked into, but if the server that is harvesting for the account is known, it would be nice if there was an API so that the server could be queried, "are you harvesting currently for x account". Then if so, the Status would go to green and harvesting, if not, then some kind of error message and suggestion to switch nodes.

### LINKED ISSUE #103: Making encrypted messages with iOS app, can't read on desktop app or mobile app
**Steps to reproduce**
make an encrypted message, later try to read it. 

**Current behavior**
the message is blank.  not sure why. 

**Expected behavior**
to see the encrypted 
 
**Affected Version**
latest iOS app

### PR DESCRIPTION
**Pull request by Peersyst**
resolves #29 ,
resolves #77 ,
resolves #103 ,  

Default node is now us-west-1

### CODE REVIEW

File: src/screens/LinkedKeysDetails.js [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+import GlobalStyles from '@src/styles/GlobalStyles';
+import HarvestingService from '@src/services/HarvestingService';
+import NetworkService from '@src/services/NetworkService';
+import { Account } from 'symbol-sdk';
+
+const styles = StyleSheet.create({
+    textButton: {
+        color: GlobalStyles.color.PRIMARY,
+    },
+    qr: {
```
Comment (OlegMakarenko) [inline src/screens/LinkedKeysDetails.js:15]: redundant

**Review by OlegMakarenko — APPROVED** [review]
