### PR TITLE
Resolved #164 Transaction listener doesn't work

### LINKED ISSUE #164: Transaction listener doesn't work

### PR DESCRIPTION
**Pull request by Peersyst**
- Added function to re-open listener when closed event emitted
- Updated symbol-sdk

### CODE REVIEW

File: src/utils/commonHelpers.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+            setTimeout(() => {
+                resolve();
+            }, ms);
+        });
+    }
+
+    /**
+     * Helper method to retry opening websocket n times asynchronously
+     */
+    static async retryNTimes(listener: Listener, trials: number, interval: number) {
```
Comment (OlegMakarenko) [inline src/utils/commonHelpers.js:20]: IMO function name is not be clear enough. 

We can make the name more specefic:
`static async reconnectListener(listener: Listener, trials: number, interval: number) {` 

Or make the logic more generic to accept any callback:
`static async retryNTimes(callback: () => boolean, trials: number, interval: number) {`

**Review by OlegMakarenko — APPROVED** [review]
